### PR TITLE
[DEV] Align all scrapers 

### PR DESCRIPTION
**Pull request by amutava**
**What does this PR do?**
  - Added scraper for standard media to ensure uniformity with all the other scrapers.

**How can this be tested?**
     - Run the command : python scraper.py

**Description of the task.**
  - Added a standard.py file that does the scraping for standard media as opposed to the initial 
  implementation.

### CODE REVIEW

**Comment by DavidLemayian** [comment]
@andela-amutava Did you pull the latest changes that are in develop? Also this should be to the `develop` branch. Another trick: reference the issue like so - #6

**Comment by amutava** [comment]
@DavidLemayian  I have changed the base branch to develop. I have pulled from develop branch. Thanks.

**Review by DavidLemayian — APPROVED** [review]
This is looking a lot tidier @andela-amutava.

I'll accept it but the branch from which I'm seeing it coming from isn't correct (`andela-amutava:ch-catch-invalidurl-errors`). Watch out for this next time.

**Comment by DavidLemayian** [comment]
Fixes #6.

**Comment by amutava** [comment]
Noted. I'm improving on my github skills. It  is a great challenge and I'm learning a lot. Thanks.

**Pull request merged**
